name: C/C++ CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v1

      - name: configure
        run: cd ..; mkdir build; cd build
      
      - name: Gen cmake cache
        run: cmake -G Ninja DCMAKE_BUILD_TYPE=Debug ../TestXmlParser
      - name: Build
        run: cmake --build build
        
      - name: try run
        run: cd bin; ./TestXerces
        
