name: C/C++ CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@v1
      
    - name: configure
      run: cd .. && mkdir build && cd build
      
    - name: Build on Linux
      run: cmake -G Ninja DCMAKE_BUILD_TYPE=Debug ../TestXmlParser
    - name: ninja build
      run: ninja --version -j 8
      
    - name: try run
      #run: cd bin && ./TestXerces
      run: ls
      
