name: C/C++ CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v1

      - name: configure
        run: cd ..; mkdir build; cd build
      
      - name: Gen cmake cache for Windows
        run: cmake -G "Visual Studio 15 2017" DCMAKE_BUILD_TYPE=Debug ../TestXmlParser
      - name: Build on Windows
        run: cmake --build . --parallel 8 --config Release
        
      - name: Try run
        run: cd bin; ./TestXerces
        
