name: C/C++ CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      
    - name: configure
      run: apt install ninja-build && cd .. && mkdir build && cd build
      
    - name: Build on Linux
      run: cmake -G Ninja DCMAKE_BUILD_TYPE=Debug ../TestXmlParser
    - name: ninja build
      run: ninja -V -j 8
      
    - name: try run
      run: cd bin && ./TestXerces
  
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: configure
        run: choco install ninja; cd ..; mkdir build; cd build
      
      - name: Build on Windows
        run: cmake -G Ninja DCMAKE_BUILD_TYPE=Debug ../TestXmlParser
      - name: ninja build
        run: ninja -V -j 8
        
      - name: try run
        run: cd bin; ./TestXerces
        
